### ISSUE TITLE
Missing "index.js"

### ISSUE THREAD

**Issue by kencarabello** [payid-org/payid#587] opened 2020-07-07 15:24 UTC
Hello.
According to the "package.json" file, there needs to be a "index.js" file (line 16, and line 26)
Can someone please add this file to the repo?
Thanks.
Ken

## Expected Behavior

please add correctly coded "index.js" to repository

## Context

Payid server will not start. At least not from AWS EC2.
I am trying to run a PayID server on AWS.

## Potential Solution

add correctly coded "inex.js" file

## Steps to Reproduce

1. Step one
2. Step two
3. Step three

## Environment

- Node version:
- NPM version:
- Operating System and version:
- PayID server version:
- PayID Version header (if applicable):

## Bonus

**Are you willing to submit a pull request to fix this bug?**

**Comment by dino-rodriguez** [comment] 2020-07-07 15:44
@kencarabello 

Ah, that's the build output after you compile the typescript to javascript.

You should only need to do this if you want to develop locally for PayID, if you want to run PayID, running :

`npm run devEnvUp` should be sufficient.


Could you try pulling down the repo and running :

`npm install` ( to install all the dependencies )

and then

`npm run build` to build the application and see if that solves the problem of the missing index file ?

You should be able to run any of the scripts in the `package.json` with :

`npm run <script name>` ( insert the script name of your choice from the `package.json`

**Comment by kencarabello** [comment] 2020-07-07 16:02
Hey, Dino.
I've got everything you're saying except "pull down the repo".
Does that mean remove it from the EC2 and start again?
In the mean time I will try those SSH commands that you gave me.
Thanks for the help.

**Comment by kencarabello** [comment] 2020-07-07 16:04
If you just mean: "npm devDown", then no problem.

**Comment by kencarabello** [comment] 2020-07-07 16:10
okay.

I ran npm devDown
Then npm install. That went fine.
But npm run build looks like it failed.
And npm run index.js failed also.
And when I nano into index.js, the file is empty.

**Comment by kencarabello** [comment] 2020-07-07 16:14
Just tried to npm run devEnvUp again.

This was one of the first lines that came back:
Cannot find a tsconfig.json file at the specified directory

**Comment by kencarabello** [comment] 2020-07-07 16:18
I got it, bro!
Thanks!
Shout from Vietnam!

**Comment by kencarabello** [comment] 2020-07-07 16:20
I copied the tsconfig.json from git hub, and pasted it into the EC2 file - which for some reason was blank.
As were many others. Have a good one.
Peace!

**Comment by hbergren** [comment] 2020-07-07 19:19
Hey @kencarabello , do you mind if we close this issue?

It looks like you got everything working, and without steps to reproduce the issue, it's not clear what the next steps are.

**Comment by kencarabello** [comment] 2020-07-07 20:09
Yes. Sure you can close it. Thanks.

**Comment by kencarabello** [comment] 2020-07-07 20:11
Wait please. One last thing:

curl: (7) Failed to connect to 127.0.0.1 port 8081

**Comment by hbergren** [comment] 2020-07-07 21:26
I'm going to leave https://github.com/payid-org/payid/issues/589 as the issue for your curl problem and close this one.

**Closed by hbergren** 2020-07-07 21:26 UTC

**Comment by kencarabello** [comment] 2020-07-07 21:28
Ok no prob. Thanks.
